// Package completion generates shell completion functions for toggle-display.
package completion

import (
	"fmt"
	"strings"
)

// Generate returns a completion script for a supported shell. Completion
// scripts query the CLI's read-only --complete endpoint rather than parsing
// human output or querying displayplacer.
func Generate(shell string) (string, error) {
	switch strings.ToLower(strings.TrimSpace(shell)) {
	case "zsh":
		return zshScript, nil
	default:
		return "", fmt.Errorf("unsupported completion shell %q (currently supported: zsh)", shell)
	}
}

const zshScript = `#compdef toggle-display

# Generated by toggle-display --completion zsh.
# The helper endpoint reads JSON only; it never invokes displayplacer.

_toggle_display_config_args() {
  reply=()
  local i
  for (( i = 2; i <= CURRENT; i++ )); do
    case "${words[i]}" in
      --config)
        if (( i < CURRENT )); then
          reply+=(--config "${words[i+1]}")
          (( i++ ))
        fi
        ;;
      --config=*)
        reply+=(--config "${words[i]#--config=}")
        ;;
    esac
  done
}

_toggle_display_selected_profile() {
  reply=()
  local i
  for (( i = 2; i < CURRENT; i++ )); do
    case "${words[i]}" in
      --profile)
        if (( i + 1 < CURRENT )); then
          reply+=("${words[i+1]}")
          (( i++ ))
        fi
        ;;
      --profile=*)
        reply+=("${words[i]#--profile=}")
        ;;
    esac
  done
}

_toggle_display_ids() {
  local kind=$1
  shift
  local command_name=${words[1]:-toggle-display}
  local -a values
  values=("${(@f)$(command "$command_name" --complete "$kind" "$@" 2>/dev/null)}")
  if (( ${#values} == 1 )) && [[ -z ${values[1]} ]]; then
    values=()
  fi
  if (( ${#values} )); then
    _describe "$kind" values
  else
    _message "no configured $kind"
  fi
}

_toggle-display() {
  local state state_descr line selected_profile
  local -a config_args
  typeset -A opt_args

  _toggle_display_config_args
  config_args=("${reply[@]}")

  _arguments -C \
    '(-h --help)'{-h,--help}'[show help]' \
    '--profile[select a monitor profile]:profile:->profile' \
    '--save[save the current arrangement]:layout:->save' \
    '--apply[apply one layout]:layout:->apply' \
    '--name[friendly layout name]' \
    '--description[layout description]' \
    '--tag[set profile metadata]:tag' \
    '--list[list profiles and layouts]' \
    '--migrate[import the old Bash configuration]' \
    '--force[replace config during migration]' \
    '--config[configuration file]:config:_files' \
    '--legacy-config[old layouts.conf path]:legacy config:_files' \
    '--completion[generate shell completion]:shell:(zsh)' \
    '--complete[completion data endpoint]:kind:(profiles layouts)'

  case $state in
    profile)
      _toggle_display_ids profiles "${config_args[@]}"
      ;;
    save|apply)
      _toggle_display_selected_profile
      if (( ${#reply} == 0 )); then
        _message 'complete --profile first'
      else
        selected_profile=${reply[-1]}
        _toggle_display_ids layouts "${config_args[@]}" --profile "$selected_profile"
      fi
      ;;
  esac
}
`
